### PR TITLE
Bugfix/fix local build issue

### PR DESCRIPTION
**Pull request by ugudlado**
**Context**
I was trying to build locally and faced few issues.

**Issues**
- README was not updated with instructions. So, had to figure out to build and run.
- Versions were not locked so there is good chance we might have issues with version differences later
- yarn build was failing because of few issues.

**Fixes**
- Updated README with instructions to install dependencies and run locally
- Added asdf instructions to lock on node and yarn versions
- Fixed yarn build and production build should work for everyone now and should be deployable anytime.

### CODE REVIEW

**Comment by Mohmed-Refaay** [comment]
Great work. btw we are using npm for installing packages in this project. 
We already had a lock file `package-lock.json`, so please remove `yarn` and let's stick to npm. 
Thank you!

**Comment by ugudlado** [comment]
> Great work. btw we are using npm for installing packages in this project. We already had a lock file `package-lock.json`, so please remove `yarn` and let's stick to npm. Thank you!
@Mohmed-Refaay 
I realized late as README had yarn in it. I reverted that change. Please review and let me know if you have any other comments.

**Comment by Mohmed-Refaay** [comment]
> > Great work. btw we are using npm for installing packages in this project. We already had a lock file `package-lock.json`, so please remove `yarn` and let's stick to npm. Thank you!
> > @Mohmed-Refaay
> > I realized late as README had yarn in it. I reverted that change. Please review and let me know if you have any other comments.

Thank you for the quick fix. 
One more thing, I think `asdf` is an overkill now because we are using just `node`. Let's just use `nvm`?  What do you think?

**Comment by Mr777Nick** [comment]
What was the issue that you were having during the build process? @ugudlado 

By the way, since our initial plan for this repo was to use a normal React app that is using static files, I think we're going to use [Next.js Static Exports](https://nextjs.org/docs/pages/building-your-application/deploying/static-exports) during the build and deployment.

**Comment by ugudlado** [comment]
> What was the issue that you were having during the build process? @ugudlado
> 
> By the way, since our initial plan for this repo was to use a normal React app that is using static files, I think we're going to use [Next.js Static Exports](https://nextjs.org/docs/pages/building-your-application/deploying/static-exports) during the build and deployment.

I was not able to run `npm run build && npm start` locally unless I made these changes.

**Comment by ugudlado** [comment]
> > > Great work. btw we are using npm for installing packages in this project. We already had a lock file `package-lock.json`, so please remove `yarn` and let's stick to npm. Thank you!
> > > @Mohmed-Refaay
> > > I realized late as README had yarn in it. I reverted that change. Please review and let me know if you have any other comments.
> 
> Thank you for the quick fix. One more thing, I think `asdf` is an overkill now because we are using just `node`. Let's just use `nvm`? What do you think?

@Mohmed-Refaay asdf is general dependency resolver irrespective of tech stack without worrying above stack specific installers like nvm. It depends only on .tool-versions file. why do you think it is overkill over nvm which is similar but specific?

**Comment by Mr777Nick** [comment]
I'm kind of on the same page as @Mohmed-Refaay on this case.
Generally speaking, I think adding another step of installing the project is overkill for a small-scale project like this.

The current steps are: 
1. Installing node or nvm on the local machine (which most JS developers have already done) 
2. Run `npm install`
3. Either run `npm run dev` or `npm run build` & `npm run start`
In this case, most of the time the developers don't need to install any more tools on their machine.

Whereas if we're adding asdf, then we're adding another step before doing the above steps. Which is to install additional tools to the local machine.
Given the scale of this project, I don't think we're going to have dependency issues with the different kinds of tools that the devs are using. Either node or nvm should be enough.

There's my 2 cents. Please do enlighten me if you have any more insight about this @ugudlado

**Comment by ugudlado** [comment]
> I'm kind of on the same page as @Mohmed-Refaay on this case. Generally speaking, I think adding another step of installing the project is overkill for a small-scale project like this.
> 
> The current steps are:
> 
> 1. Installing node or nvm on the local machine (which most JS developers have already done)
> 2. Run `npm install`
> 3. Either run `npm run dev` or `npm run build` & `npm run start`
>    In this case, most of the time the developers don't need to install any more tools on their machine.
> 
> Whereas if we're adding asdf, then we're adding another step before doing the above steps. Which is to install additional tools to the local machine. Given the scale of this project, I don't think we're going to have dependency issues with the different kinds of tools that the devs are using. Either node or nvm should be enough.
> 
> There's my 2 cents. Please do enlighten me if you have any more insight about this @ugudlado

@Mr777Nick 
1. Currently, there is no way in our project to know which version of nodejs we are using. If everyone just installs different versions of nodejs, it will create unnecessary confusion between different versions. And then we have npm packages which can vary vastly among nodejs versions. This will add more complexity. For this reason, we use nvm or asdf to freeze on nodejs or any framework versions and install packages accordingly with package lock file. Using these version managers is a need and a good practice to follow irrespective of scale of project .
2. Coming to overkill part of asdf, there is nothing related to nvm which makes it superior to asdf. Asdf is just versatile enough to handle multiple frameworks. I don't see any compelling reason from any of this discussion. Its matter of preference. I don't mind sticking to nvm and will make the change accordingly as there is strong preference towards it.

cc @Mohmed-Refaay

**Comment by ugudlado** [comment]
> Oh, as for the PR, if we're going with the asdf, I was thinking of adding more instructions to the current one instead of replacing the whole README since the base framework is still Next.js and we're still going to need the link to their documentation for future developers.

@Mr777Nick We have to maintain README with specific instructions related to project but not carrying Next.js base README. You can keep links for future reference in References section. We need README as guide to project for local setup and running project but not Next.js guide. If you think we can improve it, please let me know your comments accordingly.

**Review by Mohmed-Refaay — APPROVED** [review]
Good job! LGTM

**Comment by Mr777Nick** [comment]
> > I'm kind of on the same page as @Mohmed-Refaay on this case. Generally speaking, I think adding another step of installing the project is overkill for a small-scale project like this.
> > The current steps are:
> > 
> > 1. Installing node or nvm on the local machine (which most JS developers have already done)
> > 2. Run `npm install`
> > 3. Either run `npm run dev` or `npm run build` & `npm run start`
> >    In this case, most of the time the developers don't need to install any more tools on their machine.
> > 
> > Whereas if we're adding asdf, then we're adding another step before doing the above steps. Which is to install additional tools to the local machine. Given the scale of this project, I don't think we're going to have dependency issues with the different kinds of tools that the devs are using. Either node or nvm should be enough.
> > There's my 2 cents. Please do enlighten me if you have any more insight about this @ugudlado
> 
> @Mr777Nick
> 
> 1. Currently, there is no way in our project to know which version of nodejs we are using. If everyone just installs different versions of nodejs, it will create unnecessary confusion between different versions. And then we have npm packages which can vary vastly among nodejs versions. This will add more complexity. For this reason, we use nvm or asdf to freeze on nodejs or any framework versions and install packages accordingly with package lock file. Using these version managers is a need and a good practice to follow irrespective of scale of project .
> 2. Coming to overkill part of asdf, there is nothing related to nvm which makes it superior to asdf. Asdf is just versatile enough to handle multiple frameworks. I don't see any compelling reason from any of this discussion. Its matter of preference. I don't mind sticking to nvm and will make the change accordingly as there is strong preference towards it.
> 
> cc @Mohmed-Refaay

I see, I can understand how using it might be a good idea, although my preference is still to avoid developers from installing any additional tools to run this project.

**Review by Mr777Nick — CHANGES_REQUESTED** [review]
Can we keep the documentation link to Next.js? 
Just so that future developers will know at a glance that this repo is using the Next.js framework instead of having to inspect the project structure/files first.

**Comment by ugudlado** [comment]
> Can we keep the documentation link to Next.js on the Readme? Just so that future developers will know at a glance that this repo is using the Next.js framework instead of having to inspect the project structure/files first.

@Mr777Nick 
Updated references section

**Review by jfmdev — APPROVED** [review]

**Review by Mr777Nick — APPROVED** [review]

**Pull request merged**
